"""Default values shared across the coding agent services."""

DEFAULT_MODEL_NAME = "coding-qwen-gpu"
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash"
DEFAULT_OPENAI_BASE_URL = "http://localhost:11434/v1"
DEFAULT_OPENAI_API_KEY = "ollama"

DEFAULT_WORKSPACE_DIR = "./calculator"
DEFAULT_WORKSPACE_READ_ONLY = False
DEFAULT_ALLOWED_COMMANDS = ("python3",)

DEFAULT_MAX_ITERATIONS = 20
DEFAULT_TOOL_TIMEOUT_SECONDS = 30
DEFAULT_MAX_FILE_READ_CHARS = 10_000
DEFAULT_MAX_FILE_SIZE_BYTES = 1_000_000
DEFAULT_MAX_TOOL_OUTPUT_CHARS = 20_000

DEFAULT_MCP_HOST = "0.0.0.0"
DEFAULT_MCP_PORT = 8000
DEFAULT_MCP_PATH = "/mcp"
DEFAULT_A2A_HOST = "0.0.0.0"
DEFAULT_A2A_PORT = 9000

DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_JSON = True

DEFAULT_OPIK_ENABLED = False
DEFAULT_OPIK_PROJECT_NAME = "coding-agent"
DEFAULT_OPIK_URL = "http://localhost:5173"

